### ISSUE TITLE
output a message on success?

### ISSUE THREAD

**Issue by bruce-szalwinski** [fsouza/autoflake8#35]
At the end of a successful run, it would be nice to output a message, similar to what [black](https://github.com/psf/black/blob/cae7ae3a4d32dc51e0752d4a4e885a7792a0286d/src/black/__init__.py#L567) does.

```
All done! ✨ 🍰 ✨
41 files would be left unchanged.
```

When I run autoflake8 on a directory that has no issues, I don't get any confirmation that it actually ran.

**Comment by fsouza** [comment]
Yeah we can build that. Thanks for suggesting!
