### ISSUE TITLE
Allow to use as a Python package in addition to the standalone mode

### ISSUE THREAD

**Issue by metopa** [fsouza/autoflake8#53]
`isort` can be imported as a package and then work on the given file or code (see [docs](https://github.com/PyCQA/isort#:~:text=version%20of%20Python.\)-,From%20within%20Python%3A,-import%20isort%0A%0Aisort)). It would be very convenient to have the similar feature for `autoflake8`

**Comment by fsouza** [comment]
@metopa would an API similar to isort's be enough for you?

i.e.:

```python
import autoflake8

autoflake8.file("pythonfile.py")
code = autoflake8.code("import a\nimport b\n\nprint(b.x)")
```

**Comment by metopa** [comment]
Yep 👌 
Plus, all configuration can be specified as function parameters
