### ISSUE TITLE
Why remove unused import in `__init__.py`

### ISSUE THREAD

**Issue by yasirroni** [fsouza/autoflake8#59]
While testing `autoflake8` behavior, it seems that it always assumes unused import on `__init__.py` really unused. Contrary, importing constant on `__init__.py` is a reasonable practice. You should preserve `--ignore-init-module-imports`.

**Comment by yasirroni** [comment]
Ah, it's `flake8` that doesn't like. Okay then,

**Comment by fsouza** [comment]
> While testing `autoflake8` behavior, it seems that it always assumes unused import on `__init__.py` really unused. Contrary, importing constant on `__init__.py` is a reasonable practice. You should preserve `--ignore-init-module-imports`.

Yeah you can either set noqa in the import lines or declare `__all__`. Personally, I like the latter better because it makes it clear that you're importing to export.

**Comment by yasirroni** [comment]
> > While testing `autoflake8` behavior, it seems that it always assumes unused import on `__init__.py` really unused. Contrary, importing constant on `__init__.py` is a reasonable practice. You should preserve `--ignore-init-module-imports`.
> 
> Yeah you can either set noqa in the import lines or declare `__all__`. Personally, I like the latter better because it makes it clear that you're importing to export.

Do you mind to give me an example of using all in this context? This is importing a constant from another file.
